# Unit & integration tests docker compose file

services:
  mongodb:
    image: "mongo:5.0.6"
    ports:
      - "27017:27017"
  redis:
    image: "redis:6.2.6-alpine"
    ports:
      - "6379:6379"
  worker_dev:
    build:
      context: .
      dockerfile: worker.Dockerfile
    depends_on:
      - mongodb
      - redis
    environment:
      - NODE_ENV=development
      - DEV_DB_URI=mongodb://mongodb:27017/voicemed-challenge-dev
      - DEV_REDIS_URI=redis://redis:6379/1
  app_dev:
    build:
      context: .
      dockerfile: app.Dockerfile
    depends_on:
      - mongodb
      - redis
      - worker_dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DEV_DB_URI=mongodb://mongodb:27017/voicemed-challenge-dev
      - DEV_REDIS_URI=redis://redis:6379/1

networks:
  default:
    driver: bridge