# Unit & integration tests docker compose file

services:
  mongodb:
    image: "mongo:5.0.6"
  redis:
    image: "redis:6.2.6-alpine"
  worker_test:
    build:
      context: .
      dockerfile: worker.test.Dockerfile
    depends_on:
      - mongodb
      - redis
    environment:
      - NODE_ENV=test
      - PROD_DB_URI=mongodb://mongodb:27017/voicemed-challenge-test
      - PROD_REDIS_URI=redis://redis:6379/3
  app_test:
    build:
      context: .
      dockerfile: app.test.Dockerfile
    depends_on:
      - mongodb
      - redis
      - worker_test
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=test
      - PROD_DB_URI=mongodb://mongodb:27017/voicemed-challenge-test
      - PROD_REDIS_URI=redis://redis:6379/3

networks:
  default:
    driver: bridge